
import "./globals.css";
import { Suspense } from "react";

export const metadata = {
  title: "EduSearch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div>로딩중...</div>}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
